[package]
name = "zenlink-stable-amm-rpc"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false }

jsonrpsee = { version = "0.23.2", features = ["client-core", "server", "macros"] }


sp-blockchain = { version = "39.0.0", default-features = false }
sp-api = { version = "36.0.1", default-features = false }
sp-rpc = { version = "34.0.0", default-features = false }
sp-runtime = { version = "41.1.0", default-features = false }
tower = { version = "0.4.13", features = ["util"] }

zenlink-stable-amm-runtime-api = { path = "./runtime-api", version = "0.1.0"}
